#!/bin/bash
using="$1"
A="$2"
B="$3"
shift 3

set -e -o pipefail

function fasta() {
    if [[ $2 =~ ^/ ]] || [[ -e "$2" && -f "$2" ]]; then
        if [[ $2 =~ .f(ast)?q$ ]]; then
            recs fromfastq "$2" | recs tofasta --id name
        else
            cat "$2"
        fi
    else
        printf '>%s\n%s\n' "$@"
    fi
}

if [ -t 1 ]; then
    PAGER=${PAGER:-less -SRFXi}
else
    PAGER=cat
fi

case "$using" in
    needle|diffseq|water)
        $using \
            -asequence <(fasta A "$A") \
            -bsequence <(fasta B "$B") \
            -snucleotide1 -sformat1 fasta \
            -snucleotide2 -sformat2 fasta \
            -stdout \
            -auto \
            "$@" \
            | $PAGER
        ;;
    blast)
        blastn \
            -subject <(fasta A "$A") \
            -query   <(fasta B "$B") \
            -outfmt 1 \
            "$@" \
            | $PAGER
        ;;
    muscle)
        muscle \
            -in <(cat <(fasta A "$A") <(fasta B "$B")) \
            -quiet \
            "$@" \
            | $PAGER
        ;;
    *)
        [[ -n "$using" ]] \
            && echo "Unknown method '$using'" >&2
        echo "usage: $(basename $0) <blast|needle|diffseq|muscle> <A> <B>" >&2
        exit 1
esac
