#!/bin/bash
using="$1"
A="$2"
B="$3"
shift 3

set -e -o pipefail

function fasta() {
    if [[ $2 =~ ^/ ]] || [[ -e "$2" && -f "$2" ]]; then
        if [[ $2 =~ .f(ast)?q$ ]]; then
            recs fromfastq "$2" | recs tofasta --id name
        else
            cat "$2"
        fi
    else
        printf '>%s\n%s\n' "$@"
    fi
}

function blast() {
    local A="$1"
    local B="$2"
    shift 2

    if [[ -f "$A.nhr" && -f "$A.nin" && -f "$A.nsq" ]]; then
        # It looks like we have a blast database, so let's use -db instead
        # of -subject.
        blastn \
            -db "$A" \
            -query <(fasta QUERY "$B") \
            "$@"
    else
        blastn \
            -subject <(fasta SUBJECT "$A") \
            -query   <(fasta QUERY   "$B") \
            "$@"
    fi
}

if [ -t 1 ]; then
    PAGER=${PAGER:-less -SRFXi}
else
    PAGER=cat
fi

case "$using" in
    needle|diffseq|water)
        $using \
            -asequence <(fasta A "$A") \
            -bsequence <(fasta B "$B") \
            -snucleotide1 -sformat1 fasta \
            -snucleotide2 -sformat2 fasta \
            -stdout \
            -auto \
            "$@" \
            | $PAGER
        ;;
    blast)
        if [[ ! "$@" =~ -outfmt ]]; then
            opts="-outfmt 1"
        fi

        blast "$A" "$B" $opts "$@" | $PAGER
        ;;
    blast-table)
        fields=query,subject,identity,length,mismatches,gaps_opened,qstart,qend,sstart,send,evalue,bitscore

        blast "$A" "$B" -outfmt 6 "$@" \
            | recs fromcsv -d $'\t' -k $fields \
            | recs sort -k evalue=num \
            | recs totable -k $fields \
            | $PAGER
        ;;
    muscle)
        muscle \
            -in <(cat <(fasta A "$A") <(fasta B "$B")) \
            -quiet \
            "$@" \
            | $PAGER
        ;;
    *)
        [[ -n "$using" ]] \
            && echo "Unknown method '$using'" >&2
        echo "usage: $(basename $0) <blast|needle|diffseq|muscle> <A> <B>" >&2
        exit 1
esac
